runtime: nodejs20
env: standard

instance_class: F1

handlers:
  - url: /assets/(.*\.(js|css|woff2))$
    static_files: dist/assets/\1
    upload: dist/assets/.*\.(js|css|woff2)$
    http_headers:
      Cache-Control: "public, max-age=31536000"

  - url: /(.*\.(ico|png|jpg|jpeg|gif|svg|webp))$
    static_files: dist/\1
    upload: dist/.*\.(ico|png|jpg|jpeg|gif|svg|webp)$
    http_headers:
      Cache-Control: "public, max-age=31536000"

  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html